### ISSUE TITLE
"Write after End" when scping a directory

### ISSUE THREAD

**Issue by Gooseus** [lepture/node-scp2#17]
I am attempting to copy a directory remotely using SSH and public-key method.  It will work once, and then I get this on the next attempt to upload.

```
Error: write after end
    at writeAfterEnd (_stream_writable.js:132:12)
    at ChannelStream.Writable.write (_stream_writable.js:180:5)
    at SFTP._send (/usr/local/app/node_modules/scp2/node_modules/ssh2/lib/SFTP/SFTPv3.js:1017:23)
    at SFTP.stat (/usr/local/app/node_modules/scp2/node_modules/ssh2/lib/SFTP/SFTPv3.js:750:15)
    at /usr/local/app/node_modules/scp2/lib/client.js:134:12
    at Object.async.until (/usr/local/app/node_modules/async/lib/async.js:707:13)
    at /usr/local/app/node_modules/scp2/lib/client.js:130:11
    at Client.sftp (/usr/local/app/node_modules/scp2/lib/client.js:50:5)
    at Client.mkdir (/usr/local/app/node_modules/scp2/lib/client.js:119:8)
    at /usr/local/app/node_modules/scp2/lib/client.js:257:14
```

The app then restarts and I'm able to make the request once again.  It seems like one of the streams being used isn't being closed correctly or isn't be recreated when the scp call is made again?

**Comment by bschaepper** [comment]
Is there going to be an updated version available via npm any time soon? would be great :-)

**Comment by lepture** [comment]
@bschaepper 0.2.1 is released.
